model: DKL

#standard settings
epochs: 20  #200
task_batch_size: 1 #must be 1 for few-shot training
optimizer: Adam
lr: 0.1 #0.1 for toy Gaussian
lr_decay: 0.7
lr_step: 20
checkpoint_dir: checkpoint_dir/DKT
val_freq: 1 # validation frequency
num_workers: 8

### DKT-specific settings ###
#kernel network parameters
feature_hidden_layers: [8,4] #[128,32]

#Few-shot training settings
k_shot: [1, 2,3,4,5]

#GP params
GP_model_type: 'exact' #'exact' #'approximate'
kernel: 'RBFKernel' #'SpectralMixtureKernel'
GP_input_dim: 10

