model: FewShotSR

#standard settings
epochs: 2
task_batch_size: 32
optimizer: Adam
lr: 0.001
lr_decay: 0.7
lr_step: 20
k_shot: 10
checkpoint_dir: checkpoint_dir/FewShotSRImage
val_freq: 1
num_workers: 4

# architecture parameters
d_x: 128
d_y: 128
d_fk_out: 8
d_fm_out: 1
d_fb_out: 1
representation_size: 128
encoder_hlayers: [256, 256]
aggregator_hlayers: [256, 256]
decoder_hlayers: [256, 256, 128, 128]
f_b_hlayers: [128, 128]
f_k_hlayers: [128, 128]
f_m_hlayers: [128, 128]


