model: GP

#standard settings
epochs: 1
task_batch_size: 32 #
optimizer: Adam
lr: 0.1
lr_decay: 1 #0.7
lr_step: 20
checkpoint_dir: checkpoint_dir/FSGP
val_freq: 1
num_workers: 8

### GP-specific settings ###

#kernel network parameters
PCA_dim: 10
PCA: True

#GP params
GP_model_type: 'exact' #'exact' #'approximate'
kernel: 'RBFKernel' #'SpectralMixtureKernel' #'RBFKernel'
num_mixtures: 4

#Few-shot training settings
k_shot: [1, 2,3,4,5]
