#standard settings

epochs: 2000 #2000
task_batch_size: 1
optimizer: Adam
lr: 0.001
lr_decay: 0.7
lr_step: 30
checkpoint_dir: checkpoint_dir/ADKL
val_freq: 5

num_workers: 0

#Few-shot training settings
k_shot: [1, 2, 3, 4, 5]

### ADKL-specific settings ###

task_encoder_loss_weight: 0.01

#Deep Kernel params
d_x: 128
d_y: 128
GP_input_dim: 10              #how many dimensions to include in the GP input encoding of (x,task)
task_representation_dim: 4    #how many dimensions to include in the GP task encoding
encoder_hlayers: [256, 256]
aggregator_hlayers: [256, 256]
decoder_hlayers: [256, 256, 128, 128]


#GP params
kernel: 'RBFKernel' #'RBFKernel' # 'SpectralMixtureKernel'
#kernel_num_mixtures: 4
