# dataset params
num_tasks: 31
num_samples_per_task : 100
train_wind_speed_range: [0.0,3.0]
train_target_range: [1.0,5.0]
init_speed_range: [4,6]
theta_range: [0,90]
dataset_noise: 0.01

test_wind_speed_range: [0.0,3.0]
test_target_range: [1.0,5.0]