model: GP

#standard settings
epochs: 50
optimizer: Adam
lr: 0.1
lr_decay: 1.0
lr_step: 20
checkpoint_dir: checkpoint_dir/FSGP
val_freq: 1
num_workers: 0

#Few-shot training settings
k_shot: 5
#k_shot: [1, 2,3,4,5]
#num_draws_per_task: 5
#query_set_size : null  #uses all the query data if null
task_batch_size: 32 #must be 1 if k_shot is a list

### GP-specific settings ###

#kernel network parameters
PCA_dim: 10
PCA: False

#GP params
GP_model_type: 'exact' #'exact' #'approximate'
kernel: 'RBFKernel' #'SpectralMixtureKernel' #'RBFKernel'
num_mixtures: 4

