model: GP

#standard settings
epochs: 50
batch_size: 128
optimizer: Adam
lr: 0.1
lr_decay: 0.7
lr_step: 20
checkpoint_dir: checkpoint_dir/FSMOGP
val_freq: 1
num_workers: 0

#enable few-shot training
k_shot: 5

### GP-specific settings ###

#kernel network parameters
PCA_dim: 10
PCA: False

#GP params
GP_model_type: 'exact' #'exact' #'approximate'
kernel: 'RBFKernel' #'SpectralMixtureKernel' #'RBFKernel'
num_mixtures: 4

# MOGP-specific settings
multi_output: True
rank: 5
