model: DNNFineTuning

#standard settings
epochs: 200
batch_size: 128
optimizer: Adam
lr: 0.001 
checkpoint_dir: checkpoint_dir/DNNFineTuning
val_freq: 1 
num_workers: 8
lr_decay: 0.7
lr_step: 20

### DNNFineTuning-specific settings ###

#DNN hidden layers
hidden_layers: [128,32] #[128,32]
hidden_batchnorm: False
#Online fine-tuning settings
online_train_epochs: 5
online_optimizer: Adam
online_lr: 0.001

task_batch_size: 128
