#standard settings
model: ADKL

epochs: 500 
task_batch_size: 50
optimizer: Adam
lr: 0.1
lr_decay: 0.7 #0.8
lr_step: 50
checkpoint_dir: checkpoint_dir/ADKL
val_freq: 5
num_workers: 0

### ADKL-specific settings ###

#Few-shot training settings
k_shot: [1, 2, 3, 4, 5]

#Deep Kernel params
# d_x: 128
# d_y: 128
# d_out: 128
# representation_size: 256
# u_hlayers: [128, 128]
# v_hlayers: [128, 128]
# encoder_hlayers: [256, 256]
# aggregator_hlayers: [256, 256]
# decoder_hlayers: [256, 256, 128, 128]

d_x: 8
d_y: 2
d_out: 8
representation_size: 128
u_hlayers: [16]
v_hlayers: [16]
encoder_hlayers: [16]
aggregator_hlayers: [16]
decoder_hlayers: [16]

#GP params
kernel: 'RBFKernel'




