model: GP

#standard settings
epochs: 50
optimizer: Adam
lr: 0.1
lr_decay: 0.7
lr_step: 20
checkpoint_dir: checkpoint_dir/GP
val_freq: 1
num_workers: 0

### GP-specific settings ###

#kernel network parameters
PCA_dim: 10
PCA: False

#GP params
GP_model_type: 'exact' #'exact' #'approximate'
kernel: 'RBFKernel' #'SpectralMixtureKernel' #'RBFKernel'
num_mixtures: 4

